---
version: '3.8'
services:
  myjenkins:
    image: jenkins/jenkins
    ports:
      - 6060:8080
  qaserver:
    image: tomee
    ports:
      - 7070:8080
    links:
      - myjenkins:qa
  prodserver:
    image: tomee
    ports:
      - 8080:8080
    links:
      - myjenkins:prod
...
