---
version: '3.8'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    container_name: hub
  chrome:
    image: selenium/node-chrome
    ports:
      - 5901:5900
    container_name: chrome
    links:
      - hub:chrome
  firefox:
    image: selenium/node-firefox
    ports:
      - 5902:5900
    container_name: firefox
  opera:
    image: selenium/node-opera
    ports:
      - 5903:5900
    container_name: opera
...
