---
version: '3.8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: venkat

  apache:
    image: httpd
    ports:
      - 8080:80
    links:
      - mydb:httpd
  myphp:
    image: php:7.2-apache
    links:
      - mydb:mysql
      - apache:httd
...
